# Table of Contents
 <p>

In [4]:
from MongoDataLoader import MongoDataHandler
from IPython.core.display import display
import pandas as pd

In [3]:
mdh = MongoDataHandler()
mdhUserData = mdh.getUserData()
display(mdhUserData)

Retrieving user data...
Done.
Tabulating user data...
Done.

                         classification_count
user_name
黃冠筑                                        33
麟                                         327
赵云                                          1
翁楷杰                                        16
糖博士                                        56
江柏毅                                        17
江心怡                                        18
永帆                                          8
段海玥Kelly                                   80
林奕瑄                                        13
林佳儀                                        10
李家寬                                         3
張允瑄                                        57
一抹悲伤9                                      15
Юрий                                       84
Евгений                                    11
Димочело                                   11
Алёна Снопова                              59
Érico Percy                                 3
Äther                                      78
Äppelwoi                                   57
Álvaro Moreno                              48
~~~~~~                                      8
~~~~~                                      10
{purplepanda}                             121
zzzzzzzzz                                 401
zzzzdqhc                                    1
zzzenn                                      8
zzx204                                    208
zzrrkk777                                  20
...                                       ...
Gary morris                                78
A_Schnur                                    7
DulceMFernandez                           303
lsdavis                                  1146
Maritza022                                 48
DOUBLEHELIX2208                             5
I'm loving it                              25
constellationgeneration                    61
shellyma                                   28
18josd90                                   14
8molly                                     34
bigskeleton                               105
AGANESHA1937                                4
CommunistPanda                             15
GoodOlPatPat                              890
1282704                                    40
yorde                                      33
fabiolongi                                138
Lore1990                                   10
chloechurchill                            183
ANA ESTEVEZ                                16
thompc14                                   37
leftymckee                                300
KamSim                                     53
Cbhewitt                                   32
mmitch17                                   20
emhcul                                     52
xazneyezx                                   4
plastmassive                              702
1160511614                                 17

[139208 rows x 1 columns]

In [8]:
allClassifications = pd.DataFrame([found for found in mdh.collections['classifications'].find({},{"user_name": 1, "created_at" : 1, "updated_at" : 1, "_id": 1})])
display(allClassifications)

,_id,created_at,updated_at,user_name
0,504e52a1ba40af6cc2000008,2012-09-10 20:50:41.394,2013-02-05 19:32:33.624,Freethesouls
1,504e5299ba40af6cc2000007,2012-09-10 20:50:33.971,2013-02-05 19:15:43.273,Freethesouls
2,504e34550454e21d12000001,2012-09-10 18:41:25.927,2013-02-05 19:28:09.993,sebbysebastien
3,504e52a7ba40af6cc2000009,2012-09-10 20:50:47.974,2013-02-05 19:15:43.300,Freethesouls
4,504e4ce20454e21d12000005,2012-09-10 20:26:10.202,2013-02-05 19:27:54.966,NaN
5,504e4d0eba40af6cbb00000d,2012-09-10 20:26:54.594,2013-02-05 19:32:33.601,NaN
6,504e4d190454e21d12000006,2012-09-10 20:27:05.798,2013-02-05 19:32:33.612,NaN
7,504e4d2cba40af6cbb00000e,2012-09-10 20:27:24.006,2013-02-05 19:28:10.120,NaN
8,504e52b70454e21d0b00000d,2012-09-10 20:51:03.843,2013-02-05 19:15:43.343,Freethesouls
9,504e52a80454e21d0b00000b,2012-09-10 20:50:48.229,2013-02-05 19:15:43.327,Freethesouls
10,504e52acba40af6cc200000a,2012-09-10 20:50:52.823,2013-02-05 19:15:43.313,Freethesouls
11,504e52bc0454e21d0b00000e,2012-09-10 20:51:08.974,2013-02-05 19:15:43.359,Freethesouls
12,504e52c10454e21d0b00000f,2012-09-10 20:51:13.306,2013-02-05 19:15:43.373,Freethesouls
13,504e52c70454e21d0b000010,2012-09-10 20:51:19.687,2013-02-05 19:15:43.387,Freethesouls
14,504e52ce0454e21d12000007,2012-09-10 20:51:26.856,2013-02-05 19:15:43.402,Freethesouls
15,504e52d60454e21d12000008,2012-09-10 20:51:34.580,2013-02-05 19:15:43.414,Freethesouls
16,504e52dc0454e21d12000009,2012-09-10 20:51:40.588,2013-02-05 19:15:43.427,Freethesouls
17,504e52ee0454e21d1200000a,2012-09-10 20:51:58.817,2013-02-05 19:15:43.439,Freethesouls
18,504e53040454e21d1200000b,2012-09-10 20:52:20.545,2013-02-05 19:15:43.479,Freethesouls
19,504e530aba40af6cc200000c,2012-09-10 20:52:26.554,2013-02-05 19:15:43.466,Freethesouls
20,504e5305ba40af6cc200000b,2012-09-10 20:52:21.123,2013-02-05 19:15:43.452,Freethesouls
21,504e5315ba40af6cc200000d,2012-09-10 20:52:37.994,2013-02-05 19:15:43.499,Freethesouls
22,504e53160454e21d1200000c,2012-09-10 20:52:38.435,2013-02-05 19:15:43.684,Freethesouls
23,504e531dba40af6cc200000e,2012-09-10 20:52:45.242,2013-02-05 19:15:43.512,Freethesouls
24,504e53400454e21d1200000e,2012-09-10 20:53:20.451,2013-02-05 19:15:43.726,Freethesouls
25,504e53560454e21d1200000f,2012-09-10 20:53:42.962,2013-02-05 19:15:43.773,Freethesouls
26,504e5329ba40af6cc200000f,2012-09-10 20:52:57.072,2013-02-05 19:15:43.697,Freethesouls
27,504e533a0454e21d1200000d,2012-09-10 20:53:14.296,2013-02-05 19:15:43.712,Freethesouls
28,504e53640454e21d12000010,2012-09-10 20:53:56.662,2013-02-05 19:15:43.810,Freethesouls
29,504e535aba40af6cc2000011,2012-09-10 20:53:46.466,2013-02-05 19:15:43.754,Freethesouls
...,...,...,...,...
22767359,574e74724d34414290000463,2016-06-01 05:36:50.000,2016-06-01 05:36:50.452,JamesCan
22767360,574e74644d34417095000462,2016-06-01 05:36:36.000,2016-06-01 05:36:36.928,JamesCan
22767361,574e74764d34416ad900451f,2016-06-01 05:36:54.000,2016-06-01 05:36:54.478,JamesCan
22767362,574e748a4d344159bb005036,2016-06-01 05:37:14.000,2016-06-01 05:37:14.297,JamesCan
22767363,574e748e4d34416ad9004520,2016-06-01 05:37:18.000,2016-06-01 05:37:18.384,JamesCan
22767364,574e74904d34417095000463,2016-06-01 05:37:20.000,2016-06-01 05:37:21.005,NaN
22767365,574e74954d34417095000464,2016-06-01 05:37:25.000,2016-06-01 05:37:25.261,JamesCan
22767366,574e74994d34417078000456,2016-06-01 05:37:29.000,2016-06-01 05:37:29.892,JamesCan
22767367,574e74a84d34417078000457,2016-06-01 05:37:44.000,2016-06-01 05:37:44.961,JamesCan
22767368,574e74ad4d34414290000464,2016-06-01 05:37:49.000,2016-06-01 05:37:49.055,JamesCan
22767369,574e74b14d34417078000458,2016-06-01 05:37:53.000,2016-06-01 05:37:53.811,NaN
22767370,574e74b14d34414290000465,2016-06-01 05:37:53.000,2016-06-01 05:37:53.189,JamesCan
22767371,574e74c34d34416ad9004521,2016-06-01 05:38:11.000,2016-06-01 05:38:11.225,JamesCan
22767372,574e74d04d344159bb005038,2016-06-01 05:38:24.000,2016-06-01 05:38:24.104,josefajardo
22767373,574e74db4d34416ad9004522,2016-06-01 05:38:35.000,2016-06-01 05:38:36.229,JamesCan
22767374,574e74dd4d34417078000459,2016-06-01 05:38:37.000,2016-06-01 05:38:37.036,NaN
22767375,574e74e04d3441707800045a,2016-06-01 05:38:40.000,2016-06-01 05:38:40.940,NaN
22767376,574e74fb4d344142b7000419,2016-06-01 05:39:07.000,2016-06-01 05:39:07.180,NaN
22767377,574e74fd4d34416ad9004523,2016-06-01 05:39:09.000,2016-06-01 05:39:09.152,josefajardo
22767378,574e74ee4d344142b7000418,2016-06-01 05:38:54.000,2016-06-01 05:38:54.251,JamesCan
22767379,574e75024d34417095000465,2016-06-01 05:39:14.000,2016-06-01 05:39:14.915,JamesCan
22767380,574e750c4d3441707800045b,2016-06-01 05:39:24.000,2016-06-01 05:39:24.099,NaN
22767381,574e75144d344159bb005039,2016-06-01 05:39:32.000,2016-06-01 05:39:32.747,NaN
22767382,574e75064d344142e400041e,2016-06-01 05:39:18.000,2016-06-01 05:39:18.880,JamesCan
22767383,574e75064d34416ad9004524,2016-06-01 05:39:18.000,2016-06-01 05:39:18.078,NaN
22767384,574e75414d344159bb00503a,2016-06-01 05:40:17.000,2016-06-01 05:40:17.814,NaN
22767385,574e752b4d3441707800045c,2016-06-01 05:39:55.000,2016-06-01 05:39:55.912,NaN
22767386,574e75424d344159bb00503b,2016-06-01 05:40:18.000,2016-06-01 05:40:18.522,NaN
22767387,574e754f4d344159bb00503c,2016-06-01 05:40:31.000,2016-06-01 05:40:31.790,NaN
22767388,574e755e4d344142b700041a,2016-06-01 05:40:46.000,2016-06-01 05:40:46.435,josefajardo

In [9]:
allClassifications.to_pickle("classification_dump.pkl")